[book]
authors = ["comcx", "ireina7"]
language = "en"
multilingual = false
src = "src"
title = "Comcx's secret base"

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true            # enables the search feature
limit-results = 1000     # maximum number of search results
use-boolean-and = true   # multiple search terms must all match

[output.html]
mathjax-support = true
additional-css = ["./src/assets/custom.css"]

[preprocessor.katex]
after = ["links"]