[book]
authors = ["comcx", "ireina7"]
language = "en"
multilingual = false
src = "src"
title = "Comcx's secret base"

[output.html.fold]
enable = true
level = 0

[preprocessor.katex]
after = ["links"]